# Generated by Django 4.2.7 on 2024-07-10 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lesson", "0001_initial"),
        ("profile", "0004_create_dummy_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teaching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_lecturer",
                        to="profile.lecturerprofile",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lesson.lesson"
                    ),
                ),
            ],
            options={
                "db_table": "teaching",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="teaching_id_32616e_idx"),
                    models.Index(
                        fields=["lecturer"], name="teaching_lecture_718f11_idx"
                    ),
                    models.Index(
                        fields=["lecturer", "lesson"],
                        name="teaching_lecture_439d3b_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="teaching",
            constraint=models.UniqueConstraint(
                fields=("lesson", "lecturer"),
                name="teaching_lesson_lecturer_unique_together",
            ),
        ),
    ]
