# Generated by Django 4.2.7 on 2024-10-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0002_alter_lessonpricehistory_lesson"),
        ("teaching", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teaching",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_lesson",
                to="lesson.lesson",
            ),
        ),
    ]
