// ----------------------------------------------------------------------

export const paths = {
  // main
  root: "/",
  courses: "/courses",
  course: `/course`,
  posts: "/posts",
  post: `/post`,
  about: "/about",
  contact: "/contact",
  newsletter: "/newsletter-unsubscribe",

  // Marketing
  marketing: {
    root: "/other/marketing",
    services: "/other/marketing/services",
    caseStudies: "/other/marketing/case-studies",
    caseStudy: `/marketing/case-study`,
    posts: "/other/marketing/posts",
    post: `/marketing/post`,
    about: "/other/marketing/about",
    contact: "/other/marketing/contact",
  },
  // Travel
  travel: {
    root: "/other/travel",
    tours: "/other/travel/tours",
    tour: `/travel/tour`,
    checkout: "/other/travel/checkout",
    orderCompleted: "/other/travel/order-completed",
    posts: "/other/travel/posts",
    post: `/travel/post`,
    about: "/other/travel/about",
    contact: "/other/travel/contact",
  },
  // Career
  career: {
    root: "/other/career",
    jobs: "/other/career/jobs",
    job: `/career/job`,
    posts: "/other/career/posts",
    post: `/career/post`,
    about: "/other/career/about",
    contact: "/other/career/contact",
  },
  // E-commerce
  eCommerce: {
    root: "/other/e-commerce",
    products: "/other/e-commerce/products",
    product: `/e-commerce/product`,
    cart: "/other/e-commerce/cart",
    checkout: `/e-commerce/checkout`,
    orderCompleted: "/other/e-commerce/order-completed",
    wishlist: `/e-commerce/wishlist`,
    compare: `/e-commerce/compare`,
    account: {
      root: `/e-commerce/account`,
      personal: `/e-commerce/account/personal`,
      wishlist: `/e-commerce/account/wishlist`,
      vouchers: `/e-commerce/account/vouchers`,
      orders: `/e-commerce/account/orders`,
      payment: `/e-commerce/account/payment`,
    },
  },
  // Auth
  loginCover: "/other/auth/login-cover",
  loginBackground: "/other/auth/login-background",
  loginIllustration: "/other/auth/login-illustration",
  registerCover: "/other/auth/register-cover",
  registerBackground: "/other/auth/register-background",
  registerIllustration: "/other/auth/register-illustration",
  forgotPassword: "/other/auth/forgot-password",
  verify: "/other/auth/verify",
  // Common
  maintenance: "/other/maintenance",
  comingsoon: "/other/coming-soon",
  pricing01: "/other/pricing-01",
  pricing02: "/other/pricing-02",
  payment: "/other/payment",
  support: "/other/support",
  page404: "/other/error/404",
  page500: "/other/error/500",
  // Components
  components: {
    root: "/other/components",
    animate: "/other/components/animate",
    carousel: "/other/components/carousel",
    countUp: "/other/components/count-up",
    form: "/other/components/form-validation",
    icons: "/other/components/icons",
    image: "/other/components/image",
    label: "/other/components/label",
    lightbox: "/other/components/lightbox",
    markdown: "/other/components/markdown",
    megaMenu: "/other/components/mega-menu",
    navigation: "/other/components/navigation-bar",
    scroll: "/other/components/scroll",
    scrollProgress: "/other/components/scroll-progress",
    player: "/other/components/player",
    textMaxLine: "/other/components/text-max-line",
  },
  // Others
  pages: "/other/pages",
  docs: "https://zone-docs.vercel.app",
  license: "https://material-ui.com/store/license/#i-standard-license",
  minimalStore: "https://material-ui.com/store/items/minimal-dashboard",
  zoneStore: "https://mui.com/store/items/zone-landing-page/",
  figmaPreview:
    "https://www.figma.com/file/Zam9QBLhV4pZf5xtNs0Lf8/%5BPreview%5D-Zone_Web.v2.3.0?type=design&node-id=59%3A680507&mode=design&t=GCVeJci5zfUu5WCy-1",
};
