// ----------------------------------------------------------------------

export const paths = {
  // main
  root: "/",
  courses: "/courses",
  course: `/course`,
  teachers: "/teachers",
  posts: "/posts",
  post: `/post`,
  about: "/about",
  contact: "/contact",
  newsletter: "/newsletter-unsubscribe",
  cart: "/cart",
  checkout: "/checkout",
  orderCompleted: "/order-completed",
  wishlist: "/wishlist",
  account: {
    root: "/account",
    personal: "/account/personal",
    password: "/account/password",
    admin: {
      courses: {
        list: "/account/admin/courses/list",
        skills: "/account/admin/courses/skills",
        topics: "/account/admin/courses/topics",
      },
      lessons: {
        list: "/account/admin/lessons/list",
        priceHistory: "/account/admin/lessons/price-history",
        technologies: "/account/admin/lessons/technologies",
        purchases: "/account/admin/lessons/purchases",
        reviews: "/account/admin/lessons/reviews",
      },
      users: {
        list: "/account/admin/users/list",
        financeHistory: "/account/admin/users/finance-history",
      },
      earnings: "/account/admin/earnings",
    },
    teacher: {
      finance: "/account/teacher/finance",
      teaching: "/account/teacher/teaching",
      earnings: "/account/teacher/earnings",
      reviews: "/account/teacher/reviews",
      calendar: "/account/teacher/calendar",
    },
    lessons: "/account/lessons",
    reviews: "/account/reviews",
  },
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  verify: "/verify",

  // Marketing
  marketing: {
    root: "/other/marketing",
    services: "/other/marketing/services",
    caseStudies: "/other/marketing/case-studies",
    caseStudy: `/other/marketing/case-study`,
    posts: "/other/marketing/posts",
    post: `/other/marketing/post`,
    about: "/other/marketing/about",
    contact: "/other/marketing/contact",
  },
  // Travel
  travel: {
    root: "/other/travel",
    tours: "/other/travel/tours",
    tour: `/other/travel/tour`,
    checkout: "/other/travel/checkout",
    orderCompleted: "/other/travel/order-completed",
    posts: "/other/travel/posts",
    post: `/other/travel/post`,
    about: "/other/travel/about",
    contact: "/other/travel/contact",
  },
  // Career
  career: {
    root: "/other/career",
    jobs: "/other/career/jobs",
    job: `/other/career/job`,
    posts: "/other/career/posts",
    post: `/other/career/post`,
    about: "/other/career/about",
    contact: "/other/career/contact",
  },
  // E-commerce
  eCommerce: {
    root: "/other/e-commerce",
    products: "/other/e-commerce/products",
    product: `/other/e-commerce/product`,
    cart: "/other/e-commerce/cart",
    checkout: `/other/e-commerce/checkout`,
    orderCompleted: "/other/e-commerce/order-completed",
    wishlist: `/other/e-commerce/wishlist`,
    compare: `/other/e-commerce/compare`,
    account: {
      root: `/other/e-commerce/account`,
      personal: `/other/e-commerce/account/personal`,
      wishlist: `/other/e-commerce/account/wishlist`,
      vouchers: `/other/e-commerce/account/vouchers`,
      orders: `/other/e-commerce/account/orders`,
      payment: `/other/e-commerce/account/payment`,
    },
  },
  // Auth
  loginCover: "/other/auth/login-cover",
  loginBackground: "/other/auth/login-background",
  loginIllustration: "/other/auth/login-illustration",
  registerCover: "/other/auth/register-cover",
  registerBackground: "/other/auth/register-background",
  registerIllustration: "/other/auth/register-illustration",
  // Common
  maintenance: "/other/maintenance",
  comingsoon: "/other/coming-soon",
  pricing01: "/other/pricing-01",
  pricing02: "/other/pricing-02",
  payment: "/other/payment",
  support: "/other/support",
  page404: "/other/error/404",
  page500: "/other/error/500",
  // Components
  components: {
    root: "/other/components",
    animate: "/other/components/animate",
    carousel: "/other/components/carousel",
    countUp: "/other/components/count-up",
    form: "/other/components/form-validation",
    icons: "/other/components/icons",
    image: "/other/components/image",
    label: "/other/components/label",
    lightbox: "/other/components/lightbox",
    markdown: "/other/components/markdown",
    megaMenu: "/other/components/mega-menu",
    navigation: "/other/components/navigation-bar",
    scroll: "/other/components/scroll",
    scrollProgress: "/other/components/scroll-progress",
    player: "/other/components/player",
    textMaxLine: "/other/components/text-max-line",
  },
  // Others
  pages: "/other/pages",
  docs: "https://zone-docs.vercel.app",
  license: "https://material-ui.com/store/license/#i-standard-license",
  minimalStore: "https://material-ui.com/store/items/minimal-dashboard",
  zoneStore: "https://mui.com/store/items/zone-landing-page/",
  figmaPreview:
    "https://www.figma.com/file/Zam9QBLhV4pZf5xtNs0Lf8/%5BPreview%5D-Zone_Web.v2.3.0?type=design&node-id=59%3A680507&mode=design&t=GCVeJci5zfUu5WCy-1",
};
