apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: loopedupl/nginx:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          {{- if ne .Values.host "loop.edu.pl" }}
          volumeMounts:
            - name: basic-auth
              mountPath: /etc/nginx
              subPath: .htpasswd
              readOnly: true
          {{- end}}
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 400Mi
      {{- if ne .Values.host "loop.edu.pl" }}
      volumes:
        - name: basic-auth
          secret:
            secretName: auth
      {{- end}}
