apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matios94@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
