# Generated by Django 4.2.7 on 2024-07-08 09:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("technology", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField()),
                ("description", models.TextField()),
                ("duration", models.PositiveIntegerField()),
                ("github_url", models.URLField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "technologies",
                    models.ManyToManyField(
                        related_name="lesson_technologies", to="technology.technology"
                    ),
                ),
            ],
            options={
                "db_table": "lesson",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LessonPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lesson.lesson"
                    ),
                ),
            ],
            options={
                "db_table": "lesson_price_history",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="lesson_pric_id_b25865_idx"),
                    models.Index(
                        fields=["lesson"], name="lesson_pric_lesson__9106d6_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["id"], name="lesson_id_72b049_idx"),
        ),
    ]
