# Generated by Django 4.2.16 on 2024-12-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0002_technology_description"),
        ("lesson", "0002_alter_lessonpricehistory_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="technologies",
            field=models.ManyToManyField(
                blank=True,
                related_name="lesson_technologies",
                to="technology.technology",
            ),
        ),
    ]
