apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: mediafiles
          persistentVolumeClaim:
            claimName: mediafiles-pvc
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
      containers:
        - name: backend
          image: loopedupl/backend:{{ .Values.backend.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: mediafiles
              mountPath: "/usr/src/app/backend/media"
            - name: staticfiles
              mountPath: "/usr/src/app/backend/static"
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 400Mi
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: backend-config
