FROM node:18-alpine as BUILD_IMAGE

WORKDIR /usr/src/app/frontend

COPY package.json package-lock.json ./

# install dependencies
RUN npm install

COPY . .

ARG ENV=DEV
ENV NEXT_PUBLIC_ENV=$ENV

ARG API_URL=https://dev.loop.edu.pl/api
ENV NEXT_PUBLIC_API_URL=$API_URL

ARG BASE_URL=https://dev.loop.edu.pl
ENV NEXT_PUBLIC_BASE_URL=$BASE_URL

ARG GOOGLE_CLIENT_ID=570842553290-me2nmn43nr89bgglao8o3iak7i0k0reb.apps.googleusercontent.com
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID

ARG FACEBOOK_CLIENT_ID=1576703186506729
ENV NEXT_PUBLIC_FACEBOOK_CLIENT_ID=$FACEBOOK_CLIENT_ID

ARG GITHUB_CLIENT_ID=Ov23liYO60eg7EeIoiqu
ENV NEXT_PUBLIC_GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID

ARG GITHUB_REPO=https://github.com/loopedupl/
ENV NEXT_PUBLIC_GITHUB_REPO=$GITHUB_REPO

# build
RUN npm run build

# remove dev dependencies
RUN npm prune --omit=dev

FROM node:18-alpine

WORKDIR /usr/src/app/frontend

# copy from build image
COPY --from=BUILD_IMAGE /usr/src/app/frontend/package.json ./package.json
COPY --from=BUILD_IMAGE /usr/src/app/frontend/node_modules ./node_modules
COPY --from=BUILD_IMAGE /usr/src/app/frontend/next.config.js next.config.js
COPY --from=BUILD_IMAGE /usr/src/app/frontend/.next ./.next
COPY --from=BUILD_IMAGE /usr/src/app/frontend/public ./public

EXPOSE 3000
CMD ["npm", "start"]