FROM node:18-alpine as BUILD_IMAGE

WORKDIR /usr/src/app/frontend

COPY package.json package-lock.json ./

# install dependencies
RUN npm install

COPY . .

ARG ENV
ENV NEXT_PUBLIC_ENV=$ENV

ARG API_URL
ENV NEXT_PUBLIC_API_URL=$API_URL

ARG BASE_URL
ENV NEXT_PUBLIC_BASE_URL=$BASE_URL

ARG GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID

ARG FACEBOOK_CLIENT_ID
ENV NEXT_PUBLIC_FACEBOOK_CLIENT_ID=$FACEBOOK_CLIENT_ID

ARG GITHUB_CLIENT_ID
ENV NEXT_PUBLIC_GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID

ARG GITHUB_REPO
ENV NEXT_PUBLIC_GITHUB_REPO=$GITHUB_REPO

# build
RUN npm run build

# remove dev dependencies
RUN npm prune --omit=dev

FROM node:18-alpine

WORKDIR /usr/src/app/frontend

# copy from build image
COPY --from=BUILD_IMAGE /usr/src/app/frontend/package.json ./package.json
COPY --from=BUILD_IMAGE /usr/src/app/frontend/node_modules ./node_modules
COPY --from=BUILD_IMAGE /usr/src/app/frontend/next.config.js next.config.js
COPY --from=BUILD_IMAGE /usr/src/app/frontend/.next ./.next
COPY --from=BUILD_IMAGE /usr/src/app/frontend/public ./public

EXPOSE 3000
CMD ["npm", "start"]