# Generated by Django 4.2.7 on 2024-09-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile", "0004_create_dummy_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("subject", models.CharField()),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "NEW"), ("R", "READ")], default="N"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_recipient",
                        to="profile.profile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_sender",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "message",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="message_id_878984_idx"),
                    models.Index(fields=["sender"], name="message_sender__0e912c_idx"),
                    models.Index(
                        fields=["recipient"], name="message_recipie_5f6840_idx"
                    ),
                    models.Index(
                        fields=["sender", "recipient"],
                        name="message_sender__fe0c16_idx",
                    ),
                    models.Index(fields=["status"], name="message_status_fbc084_idx"),
                    models.Index(
                        fields=["status", "sender", "recipient"],
                        name="message_status_d29a45_idx",
                    ),
                ],
            },
        ),
    ]
