apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: loopedupl/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 400Mi
          envFrom:
            - secretRef:
                name: frontend-secret
            - secretRef:
                name: facebook-secret
            - secretRef:
                name: github-secret
            - secretRef:
                name: google-secret
            - configMapRef:
                name: frontend-config
