# Generated by Django 4.2.7 on 2024-09-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile", "0004_create_dummy_student"),
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event_id", models.CharField(unique=True)),
                ("url", models.URLField()),
            ],
            options={
                "db_table": "meeting",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_lecturer",
                        to="profile.lecturerprofile",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_lesson",
                        to="lesson.lesson",
                    ),
                ),
                (
                    "meeting",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "schedule",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file_id", models.CharField()),
                ("file_name", models.CharField()),
                ("file_url", models.URLField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.schedule",
                    ),
                ),
            ],
            options={
                "db_table": "recording",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(fields=["event_id"], name="meeting_event_i_4852c5_idx"),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(fields=["url"], name="meeting_url_07e4de_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["id"], name="schedule_id_75c99d_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["lecturer"], name="schedule_lecture_c3815b_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["lesson"], name="schedule_lesson__82919a_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["lesson", "lecturer"], name="schedule_lesson__c6746c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("lecturer", "start_time", "end_time"),
                name="schedule_lecturer_time_unique_together",
            ),
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(fields=["file_id"], name="recording_file_id_a54af5_idx"),
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(
                fields=["file_name"], name="recording_file_na_afa619_idx"
            ),
        ),
    ]
