# Generated by Django 4.2.7 on 2024-02-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile", "0002_create_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_lecturer",
                        to="profile.profile",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_lesson",
                        to="lesson.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "schedule",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="schedule_id_75c99d_idx"),
                    models.Index(
                        fields=["lecturer"], name="schedule_lecture_c3815b_idx"
                    ),
                    models.Index(fields=["lesson"], name="schedule_lesson__82919a_idx"),
                    models.Index(
                        fields=["lesson", "lecturer"],
                        name="schedule_lesson__c6746c_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("lecturer", "start_time", "end_time"),
                name="schedule_lecturer_time_unique_together",
            ),
        ),
    ]
