# Generated by Django 4.2.7 on 2024-07-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="meeting_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
