# Generated by Django 4.2.7 on 2024-08-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="meeting_url",
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event_id", models.CharField(unique=True)),
                ("url", models.URLField()),
            ],
            options={
                "db_table": "meeting",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["event_id"], name="meeting_event_i_4852c5_idx"
                    ),
                    models.Index(fields=["url"], name="meeting_url_07e4de_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="schedule",
            name="meeting",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.meeting",
            ),
        ),
    ]
