# Generated by Django 4.2.7 on 2023-11-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["id"], name="schedule_id_75c99d_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["lesson"], name="schedule_lesson__82919a_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["lecturer"], name="schedule_lecture_c3815b_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["lesson", "lecturer"], name="schedule_lesson__c6746c_idx"
            ),
        ),
    ]
