# Generated by Django 4.2.7 on 2024-09-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_remove_schedule_meeting_url_meeting_schedule_meeting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file_id", models.CharField()),
                ("file_name", models.CharField()),
                ("file_url", models.URLField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.schedule",
                    ),
                ),
            ],
            options={
                "db_table": "recording",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["file_id"], name="recording_file_id_a54af5_idx"
                    ),
                    models.Index(
                        fields=["file_name"], name="recording_file_na_afa619_idx"
                    ),
                ],
            },
        ),
    ]
