from django.conf import settings
from datetime import datetime, timedelta
from django.utils.timezone import make_aware

LOCAL = settings.LOCAL

FRONTEND_URL = settings.BASE_FRONTEND_URL

ADMIN_EMAIL = settings.ADMIN_EMAIL
ADMIN_PASSWORD = settings.ADMIN_PASSWORD

CONTACT_EMAIL = settings.CONTACT_EMAIL
NOREPLY_EMAIL = settings.NOREPLY_EMAIL
MEETINGS_EMAIL = settings.MEETINGS_EMAIL

DEFAULT_COUPON = {
    "code": "programista20",
    "discount": 20,
    "is_percentage": True,
    "all_users": True,
    "is_infinite": True,
    "uses_per_user": 1,
    "active": True,
    "expiration_date": make_aware(datetime.now() + timedelta(weeks=52 * 99)),
}

WORDS_PER_MINUTE = 250

DUMMY_LECTURER_EMAIL = settings.DUMMY_LECTURER_EMAIL
DUMMY_LECTURER_PASSWORD = settings.DUMMY_LECTURER_PASSWORD

DUMMY_STUDENT_EMAIL = settings.DUMMY_STUDENT_EMAIL
DUMMY_STUDENT_PASSWORD = settings.DUMMY_STUDENT_PASSWORD

GOOGLE_CLIENT_ID = settings.GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET = settings.GOOGLE_CLIENT_SECRET

FACEBOOK_CLIENT_ID = settings.FACEBOOK_CLIENT_ID
FACEBOOK_CLIENT_SECRET = settings.FACEBOOK_CLIENT_SECRET

GITHUB_CLIENT_ID = settings.GITHUB_CLIENT_ID
GITHUB_CLIENT_SECRET = settings.GITHUB_CLIENT_SECRET

GOOGLE_CREDENTIALS = settings.GOOGLE_CREDENTIALS

GITHUB_REPO = settings.GITHUB_REPO

MESSAGE_EXPIRY_DAYS = 31
NOTIFICATION_EXPIRY_DAYS = 31

MIN_PASSWORD_LENGTH = settings.MIN_PASSWORD_LENGTH
LESSON_DURATION_MULTIPLIER = settings.LESSON_DURATION_MULTIPLIER
CANCELLATION_TIME = settings.CANCELLATION_TIME
REMINDER_TIME = settings.REMINDER_TIME
MIN_STUDENTS_THRESHOLD = settings.MIN_STUDENTS_THRESHOLD

PAYMENT_SERVER = settings.PAYMENT_SERVER
PAYMENT_MERCHANT_ID = settings.PAYMENT_MERCHANT_ID
PAYMENT_STORE_ID = settings.PAYMENT_STORE_ID
PAYMENT_CRC = settings.PAYMENT_CRC
PAYMENT_API_KEY = settings.PAYMENT_API_KEY
