# Generated by Django 4.2.7 on 2024-09-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField()),
                (
                    "lessons",
                    models.ManyToManyField(
                        related_name="module_lessons", to="lesson.lesson"
                    ),
                ),
            ],
            options={
                "db_table": "module",
                "ordering": ["id"],
                "indexes": [models.Index(fields=["id"], name="module_id_820996_idx")],
            },
        ),
    ]
