# Generated by Django 4.2.7 on 2024-02-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lesson", "0001_initial"),
        ("profile", "0002_create_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lesson.lesson"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_student",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "cart",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="cart_id_32fa18_idx"),
                    models.Index(fields=["student"], name="cart_student_3cd948_idx"),
                    models.Index(
                        fields=["student", "lesson"], name="cart_student_a7b40b_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("lesson", "student"), name="cart_lesson_student_unique_together"
            ),
        ),
    ]
