# Generated by Django 4.2.5 on 2023-10-14 15:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile", "0002_create_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("description", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("P", "Podstawowy"),
                            ("Ś", "Średniozaawansowany"),
                            ("Z", "Zaawansowany"),
                            ("E", "Ekspert"),
                        ],
                        null=True,
                    ),
                ),
                ("github_repo_link", models.URLField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "skill",
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "technology",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "topic",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("description", models.TextField()),
                ("duration", models.PositiveIntegerField()),
                ("github_branch_link", models.URLField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="course.course",
                    ),
                ),
                (
                    "lecturers",
                    models.ManyToManyField(
                        related_name="lesson_lecturers", to="profile.profile"
                    ),
                ),
            ],
            options={
                "db_table": "lesson",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="skills",
            field=models.ManyToManyField(
                related_name="course_skills", to="course.skill"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="technology",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technology",
                to="course.technology",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="topics",
            field=models.ManyToManyField(
                related_name="course_topics", to="course.topic"
            ),
        ),
    ]
