# Generated by Django 4.2.7 on 2024-02-15 13:58

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "topic",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="topic_id_f75fc5_idx"),
                    models.Index(fields=["name"], name="topic_name_bfb54a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "skill",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="skill_id_0bf196_idx"),
                    models.Index(fields=["name"], name="skill_name_e8acf2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField()),
                ("description", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("P", "Podstawowy"),
                            ("Ś", "Średniozaawansowany"),
                            ("Z", "Zaawansowany"),
                            ("E", "Ekspert"),
                        ],
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(upload_to=course.models.course_directory_path),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=course.models.course_directory_path,
                    ),
                ),
                (
                    "lessons",
                    models.ManyToManyField(
                        related_name="course_lessons", to="lesson.lesson"
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        related_name="course_skills", to="course.skill"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        related_name="course_topics", to="course.topic"
                    ),
                ),
            ],
            options={
                "db_table": "course",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="course_id_1077aa_idx"),
                    models.Index(fields=["level"], name="course_level_129141_idx"),
                ],
            },
        ),
    ]
