# Generated by Django 4.2.7 on 2024-01-09 13:40

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=course.models.course_directory_path
            ),
        ),
    ]
