# Generated by Django 4.2.7 on 2023-11-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["id"], name="course_id_1077aa_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["technology"], name="course_technol_44f663_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["level"], name="course_level_129141_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["price"], name="course_price_e0abd1_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["technology", "level", "price"],
                name="course_technol_8c2153_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["technology", "level"], name="course_technol_63c80f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["technology", "price"], name="course_technol_c86a02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["level", "price"], name="course_level_8e6c37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["id"], name="lesson_id_72b049_idx"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["course"], name="lesson_course__c4014c_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["id"], name="skill_id_0bf196_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["name"], name="skill_name_e8acf2_idx"),
        ),
        migrations.AddIndex(
            model_name="technology",
            index=models.Index(fields=["id"], name="technology_id_74ed03_idx"),
        ),
        migrations.AddIndex(
            model_name="technology",
            index=models.Index(fields=["name"], name="technology_name_ef7438_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["id"], name="topic_id_f75fc5_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["name"], name="topic_name_bfb54a_idx"),
        ),
    ]
