# Generated by Django 4.2.7 on 2024-09-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("module", "0001_initial"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="lessons",
            field=models.ManyToManyField(
                related_name="course_modules", to="module.module"
            ),
        ),
    ]
