# Generated by Django 4.2.16 on 2024-12-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0002_rename_skill_tag_and_more"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="skills",
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(related_name="course_tags", to="tag.tag"),
        ),
    ]
