# Generated by Django 4.2.7 on 2024-02-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_alter_course_video"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="course",
            name="course_technol_44f663_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="course_technol_8c2153_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="course_technol_63c80f_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="course_technol_c86a02_idx",
        ),
        migrations.RemoveField(
            model_name="course",
            name="technology",
        ),
        migrations.AddField(
            model_name="course",
            name="technology",
            field=models.ManyToManyField(
                related_name="technology", to="course.technology"
            ),
        ),
    ]
