# Generated by Django 4.2.16 on 2024-12-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_remove_course_skills_course_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="overview",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
