# Generated by Django 4.2.7 on 2024-09-05 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_alter_course_lessons"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="lessons",
            new_name="modules",
        ),
    ]
