# Generated by Django 4.2.7 on 2023-11-15 09:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_course_course_id_1077aa_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.lesson"
                    ),
                ),
            ],
            options={
                "db_table": "lesson_price_history",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="lesson_pric_id_b25865_idx"),
                    models.Index(
                        fields=["lesson"], name="lesson_pric_lesson__9106d6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CoursePriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
            options={
                "db_table": "course_price_history",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="course_pric_id_e0da53_idx"),
                    models.Index(
                        fields=["course"], name="course_pric_course__1bf2cc_idx"
                    ),
                ],
            },
        ),
    ]
