# Generated by Django 4.2.16 on 2024-12-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0001_initial"),
        ("course", "0003_course_overview"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="candidates",
            field=models.ManyToManyField(
                related_name="course_candidates", to="candidate.candidate"
            ),
        ),
    ]
