# Generated by Django 4.2.16 on 2025-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_course_candidates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("Podstawowy", "Basic"),
                    ("Średniozaawansowany", "Intermediate"),
                    ("Zaawansowany", "Advanced"),
                    ("Ekspert", "Expert"),
                ],
                null=True,
            ),
        ),
    ]
