# Generated by Django 4.2.7 on 2024-10-08 13:40

from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile", "0004_create_dummy_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "post_category",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="post_catego_id_034a96_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField()),
                ("description", models.TextField()),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to=post.models.post_directory_path)),
                ("visits", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=False)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="post_authors", to="profile.lecturerprofile"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="post.postcategory",
                    ),
                ),
            ],
            options={
                "db_table": "post",
                "ordering": ["id"],
                "indexes": [models.Index(fields=["id"], name="post_id_1bcbbb_idx")],
            },
        ),
    ]
