# Generated by Django 4.2.16 on 2024-12-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0002_rename_skill_tag_and_more"),
        ("post", "0002_alter_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="post_tags", to="tag.tag"),
        ),
    ]
