# Generated by Django 4.2.16 on 2024-12-18 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="publication_date",
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
