# Generated by Django 4.2.16 on 2024-12-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "candidate",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["id"], name="candidate_id_96f53f_idx"),
                    models.Index(fields=["name"], name="candidate_name_5539eb_idx"),
                ],
            },
        ),
    ]
