apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loopdev

spec:
  rules:
    - host: www.loopdev.edu.pl
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: loopdev
                port:
                  number: 80
