# Generated by Django 4.2.7 on 2024-07-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lesson", "0001_initial"),
        ("profile", "0001_initial"),
        ("purchase", "0001_initial"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_lesson",
                        to="lesson.lesson",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_purchase",
                        to="purchase.purchase",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_schedule",
                        to="schedule.schedule",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_student",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "reservation",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="reservation_id_199ba1_idx"),
                    models.Index(
                        fields=["student"], name="reservation_student_495e0c_idx"
                    ),
                    models.Index(
                        fields=["schedule"], name="reservation_schedul_a9bf15_idx"
                    ),
                    models.Index(
                        fields=["purchase"], name="reservation_purchas_23169b_idx"
                    ),
                    models.Index(
                        fields=["student", "lesson"],
                        name="reservation_student_13ad0b_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("student", "lesson", "schedule", "purchase"),
                name="reservation_student_lesson_schedule_purchase_unique_together",
            ),
        ),
    ]
