# Generated by Django 4.2.7 on 2024-07-10 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reservation", "0001_initial"),
        ("schedule", "0001_initial"),
        ("profile", "0004_create_dummy_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_schedule",
                to="schedule.schedule",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_student",
                to="profile.studentprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["id"], name="reservation_id_199ba1_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["student"], name="reservation_student_495e0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["schedule"], name="reservation_schedul_a9bf15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["purchase"], name="reservation_purchas_23169b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["student", "lesson"], name="reservation_student_13ad0b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("student", "lesson", "schedule", "purchase"),
                name="reservation_student_lesson_schedule_purchase_unique_together",
            ),
        ),
    ]
