# Generated by Django 4.2.7 on 2024-02-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reservation",
            name="reservation_student_lesson_schedule_unique_together",
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("student", "schedule"),
                name="reservation_student_lesson_schedule_unique_together",
            ),
        ),
    ]
