apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
  labels:
    app: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: mediafiles
          persistentVolumeClaim:
            claimName: mediafiles-pvc
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
      containers:
        - name: nginx
          image: loopedupl/nginx:{{ .Values.nginx.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mediafiles
              mountPath: "/usr/src/app/backend/media"
            - name: staticfiles
              mountPath: "/usr/src/app/backend/static"
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 400Mi
