# Generated by Django 4.2.7 on 2024-04-15 14:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile", "0002_create_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedUsersRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("all_users", models.BooleanField(default=False)),
                ("users", models.ManyToManyField(blank=True, to="profile.profile")),
            ],
            options={
                "db_table": "coupon_allowed_users_rule",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code", models.CharField(max_length=36, unique=True)),
                ("times_used", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.IntegerField(default=0)),
                ("is_percentage", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "coupon_discount",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MaxUsageRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("max_uses", models.BigIntegerField(default=0)),
                ("is_infinite", models.BooleanField(default=False)),
                ("uses_per_user", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "coupon_usage_rule",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MinPurchaseTotalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "min_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "coupon_min_purchase_total_rule",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ValidityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expiration_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "coupon_validity_rule",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Rules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allowed_users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coupon.allowedusersrule",
                    ),
                ),
                (
                    "max_usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coupon.maxusagerule",
                    ),
                ),
                (
                    "min_purchase_total",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coupon.minpurchasetotalrule",
                    ),
                ),
                (
                    "validity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coupon.validityrule",
                    ),
                ),
            ],
            options={
                "db_table": "coupon_rules",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CouponUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("times_used", models.IntegerField(default=0)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="coupon.coupon"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "coupon_user",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="coupon.discount"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="rules",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="coupon.rules"
            ),
        ),
    ]
