# Generated by Django 4.2.7 on 2024-09-24 08:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile", "0004_create_dummy_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "code",
                    models.CharField(
                        max_length=36,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
                ("discount", models.IntegerField(default=0)),
                ("is_percentage", models.BooleanField(default=False)),
                ("all_users", models.BooleanField(default=False)),
                ("max_uses", models.BigIntegerField(default=0)),
                ("is_infinite", models.BooleanField(default=False)),
                ("uses_per_user", models.IntegerField(default=1)),
                ("expiration_date", models.DateTimeField()),
                ("active", models.BooleanField(default=False)),
                (
                    "min_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(blank=True, to="profile.studentprofile"),
                ),
            ],
            options={
                "db_table": "coupon",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CouponUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="coupon.coupon"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "coupon_user",
                "ordering": ["id"],
            },
        ),
    ]
