# Generated by Django 4.2.7 on 2024-10-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0004_create_dummy_student"),
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponuser",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_user_coupon",
                to="coupon.coupon",
            ),
        ),
        migrations.AlterField(
            model_name="couponuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_user_student",
                to="profile.studentprofile",
            ),
        ),
    ]
