# Generated by Django 4.2.16 on 2024-10-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0004_alter_purchase_lesson_alter_purchase_payment_and_more"),
        ("coupon", "0003_add_default_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponuser",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_user_payment",
                to="purchase.payment",
            ),
            preserve_default=False,
        ),
    ]
