backend:
  tag: latest.prod
  replicas: 1
  storage:
    staticfiles:
      size: 1Gi
      volumeHandle: e277f7e1-f0be-41d9-8d27-7ce9e8d05da3
    mediafiles:
      size: 1Gi
      volumeHandle: 3a2a4de0-0ad3-468b-99ae-8e4d13b69282
  env:
    CSRF_TRUSTED_ORIGINS: "https://loop.edu.pl,https://www.loop.edu.pl"
    ALLOWED_HOST: "loop.edu.pl,www.loop.edu.pl"
    BASE_URL: "https://www.loop.edu.pl"

frontend:
  tag: latest.prod
  replicas: 1

nginx:
  tag: latest.prod
  replicas: 1
  host: loop.edu.pl
