backend:
  tag: latest.uat
  replicas: 1
  env:
    ENV: "UAT"
    CSRF_TRUSTED_ORIGINS: "https://uat.loop.edu.pl,https://www.uat.loop.edu.pl"
    ALLOWED_HOST: "uat.loop.edu.pl,www.uat.loop.edu.pl"
    BASE_URL: "https://uat.loop.edu.pl"
    PAYMENT_SERVER: "https://sandbox.przelewy24.pl"

frontend:
  tag: latest.uat
  replicas: 1

nginx:
  tag: latest.uat
  replicas: 1
  host: uat.loop.edu.pl

pgbouncer:
  enabled: true
  tag: latest
  replicas: 1
