apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
        - name: mediafiles
          persistentVolumeClaim:
            claimName: mediafiles-pvc
      containers:
        - name: backend
          image: loopedupl/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: staticfiles
              mountPath: "/usr/src/app/backend/static"
            - name: mediafiles
              mountPath: "/usr/src/app/backend/media"
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 400Mi
          envFrom:
            - secretRef:
                name: backend-secret
            - secretRef:
                name: email-secret
            - secretRef:
                name: facebook-secret
            - secretRef:
                name: github-secret
            - secretRef:
                name: google-secret
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: backend-config
