apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: loopedupl/backend:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: media-volume
              mountPath: /usr/src/app/backend/media
          envFrom:
            - secretRef:
                name: backend-secret
            - secretRef:
                name: email-secret
            - secretRef:
                name: facebook-secret
            - secretRef:
                name: github-secret
            - secretRef:
                name: google-secret
            - secretRef:
                name: postgre-secret
            - configMapRef:
                name: backend-config
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-volume
