apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediafiles-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/src/app/backend/media"
