apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediafiles-pvc
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: mediafiles-pv
