# Generated by Django 4.2.7 on 2024-04-03 13:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0002_create_superuser"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.CharField(
                        max_length=26,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(26)],
                    ),
                ),
                (
                    "commission",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_history_lecturer",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "finance_history",
                "ordering": ["lecturer"],
                "indexes": [
                    models.Index(fields=["id"], name="finance_his_id_46302c_idx"),
                    models.Index(
                        fields=["lecturer"], name="finance_his_lecture_381420_idx"
                    ),
                ],
            },
        ),
    ]
