# Generated by Django 4.2.16 on 2025-02-11 12:36

from django.db import migrations, models
import django.db.models.deletion
import service_purchase.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("service", "0001_initial"),
        ("profile", "0006_create_dummy_other"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.UUIDField(default=uuid.uuid4)),
                ("order_id", models.BigIntegerField(default=None, null=True)),
                ("amount", models.IntegerField()),
                (
                    "currency",
                    models.CharField(
                        choices=[("PLN", "PLN"), ("EUR", "EUR"), ("USD", "USD")],
                        default="PLN",
                        max_length=3,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("Przelewy24", "Przelewy24"),
                            ("PayPal", "PayPal"),
                            ("Przelew", "Przelew"),
                        ],
                        default="Przelew",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("S", "Success"), ("F", "Failure")],
                        default="P",
                    ),
                ),
                ("notes", models.TextField()),
            ],
            options={
                "db_table": "service_payment",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "other",
                    models.ForeignKey(
                        on_delete=models.SET(
                            service_purchase.models.get_dummy_other_profile
                        ),
                        related_name="purchase_other",
                        to="profile.otherprofile",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_payment",
                        to="service_purchase.payment",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_service",
                        to="service.service",
                    ),
                ),
            ],
            options={
                "db_table": "service_purchase",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["id"], name="service_pay_id_16a01b_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["session_id"], name="service_pay_session_2618e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order_id"], name="service_pay_order_i_0aba14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["id"], name="service_pur_id_8a973f_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["service"], name="service_pur_service_b35968_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["other", "service"], name="service_pur_other_i_25ae4a_idx"
            ),
        ),
    ]
