# Generated by Django 4.2.7 on 2024-09-24 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile", "0004_create_dummy_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField()),
                ("subtitle", models.CharField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "NEW"), ("R", "READ")], default="N"
                    ),
                ),
                ("path", models.CharField(blank=True, null=True)),
                ("icon", models.CharField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="notificatio_id_51d1d9_idx"),
                    models.Index(
                        fields=["profile"], name="notificatio_profile_d58aea_idx"
                    ),
                    models.Index(
                        fields=["profile", "status"],
                        name="notificatio_profile_de2ddd_idx",
                    ),
                ],
            },
        ),
    ]
