# Generated by Django 4.2.7 on 2024-09-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="path",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="subtitle",
            field=models.CharField(blank=True, null=True),
        ),
    ]
