# Generated by Django 4.2.16 on 2025-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0002_alter_notification_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[("NEW", "New"), ("READ", "Read")], default="NEW"
            ),
        ),
    ]
