# Generated by Django 4.2.7 on 2024-02-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "technology",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="technology_id_74ed03_idx"),
                    models.Index(fields=["name"], name="technology_name_ef7438_idx"),
                ],
            },
        ),
    ]
