# Generated by Django 4.2.16 on 2024-12-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
