apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
data:
  ENV: {{ .Values.env.ENV }}
  BASE_URL: {{ .Values.env.BASE_URL }}
  API_URL: {{ .Values.env.API_URL }}
  GITHUB_REPO: "https://github.com/loopedupl/"
