apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: loopedupl/frontend:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config-map
              mountPath: /app/config
            - name: secrets
              mountPath: /app/secret
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 400Mi
      volumes:
        - name: config-map
          configMap:
            name: frontend-config
        - name: secrets
          secret:
            secretName: secrets
