# Generated by Django 4.2.7 on 2024-08-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "skill",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["id"], name="skill_id_0bf196_idx"),
                    models.Index(fields=["name"], name="skill_name_e8acf2_idx"),
                ],
            },
        ),
    ]
