# Generated by Django 4.2.5 on 2023-11-05 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "newsletter",
            },
        ),
    ]
