# Generated by Django 4.2.7 on 2024-07-10 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "newsletter",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="newsletter_id_7ebab6_idx"),
                    models.Index(fields=["uuid"], name="newsletter_uuid_cfeebd_idx"),
                ],
            },
        ),
    ]
