# Generated by Django 4.2.7 on 2023-11-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="newsletter",
            index=models.Index(fields=["id"], name="newsletter_id_7ebab6_idx"),
        ),
        migrations.AddIndex(
            model_name="newsletter",
            index=models.Index(fields=["uuid"], name="newsletter_uuid_cfeebd_idx"),
        ),
    ]
