# Generated by Django 4.2.7 on 2023-11-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile", "0002_create_superuser"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.lesson"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_profile",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "wishlist",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="wishlist_id_671a8c_idx"),
                    models.Index(
                        fields=["profile"], name="wishlist_profile_c5e962_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                fields=("profile", "lesson"),
                name="wishlist_profile_lesson_unique_together",
            ),
        ),
    ]
