# Generated by Django 4.2.7 on 2023-11-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schedule", "0001_initial"),
        ("course", "0001_initial"),
        ("profile", "0002_create_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_lecturer",
                        to="profile.profile",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.lesson"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_student",
                        to="profile.profile",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_time",
                        to="schedule.schedule",
                    ),
                ),
            ],
            options={
                "db_table": "wishlist",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="wishlist_id_671a8c_idx"),
                    models.Index(
                        fields=["student"], name="wishlist_student_7e9315_idx"
                    ),
                    models.Index(
                        fields=["student", "lesson"], name="wishlist_student_73e0ef_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                fields=("lesson", "student", "lecturer", "time"),
                name="wishlist_lesson_student_lecturer_time_unique_together",
            ),
        ),
    ]
