# Generated by Django 4.2.7 on 2024-02-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "topic",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["id"], name="topic_id_f75fc5_idx"),
                    models.Index(fields=["name"], name="topic_name_bfb54a_idx"),
                ],
            },
        ),
    ]
