# Generated by Django 4.2.7 on 2024-08-06 11:31

from django.db import migrations, models
import django.db.models.deletion
import purchase.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lesson", "0001_initial"),
        ("profile", "0004_create_dummy_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.UUIDField(default=uuid.uuid4)),
                ("order_id", models.BigIntegerField(null=True)),
                ("amount", models.IntegerField()),
                ("status", models.CharField(default=None, null=True)),
            ],
            options={
                "db_table": "payment",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="lesson.lesson"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchase.payment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=models.SET(purchase.models.get_dummy_student_profile),
                        related_name="lesson_purchase_student",
                        to="profile.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "purchase",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["id"], name="payment_id_fc31a4_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["session_id"], name="payment_session_9832c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["order_id"], name="payment_order_i_f08ba7_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["id"], name="purchase_id_b397cf_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["lesson"], name="purchase_lesson__e5a7b1_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["student", "lesson"], name="purchase_student_95635f_idx"
            ),
        ),
    ]
