# Generated by Django 4.2.7 on 2023-11-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schedule", "0001_initial"),
        ("purchase", "0001_initial"),
        ("course", "0001_initial"),
        ("profile", "0002_create_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonpurchase",
            name="time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="schedule.schedule"
            ),
        ),
        migrations.AddField(
            model_name="coursepurchase",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="course.course"
            ),
        ),
        migrations.AddField(
            model_name="coursepurchase",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_purchase_student",
                to="profile.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonpurchase",
            index=models.Index(fields=["id"], name="lesson_purc_id_9c301a_idx"),
        ),
        migrations.AddIndex(
            model_name="lessonpurchase",
            index=models.Index(
                fields=["lesson"], name="lesson_purc_lesson__b768f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonpurchase",
            index=models.Index(
                fields=["lecturer"], name="lesson_purc_lecture_754702_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonpurchase",
            index=models.Index(
                fields=["student", "lesson", "lecturer"],
                name="lesson_purc_student_1f44df_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonpurchase",
            constraint=models.UniqueConstraint(
                fields=("lesson", "student", "lecturer"),
                name="lesson_purchase_lesson_student_lecturer_unique_together",
            ),
        ),
        migrations.AddIndex(
            model_name="coursepurchase",
            index=models.Index(fields=["id"], name="course_purc_id_ec61b2_idx"),
        ),
        migrations.AddIndex(
            model_name="coursepurchase",
            index=models.Index(
                fields=["student"], name="course_purc_student_623063_idx"
            ),
        ),
    ]
