# Generated by Django 4.2.7 on 2024-02-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lessonpurchase",
            name="lesson_purchase_lesson_student_unique_together",
        ),
        migrations.AlterField(
            model_name="coursepurchase",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name="lessonpurchase",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
