# Generated by Django 4.2.7 on 2024-10-03 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.UUIDField(default=uuid.uuid4)),
                ("order_id", models.BigIntegerField(default=None, null=True)),
                ("amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("S", "Success"), ("F", "Failure")],
                        default="P",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="payment_id_fc31a4_idx"),
                    models.Index(
                        fields=["session_id"], name="payment_session_9832c6_idx"
                    ),
                    models.Index(
                        fields=["order_id"], name="payment_order_i_f08ba7_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="purchase",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchase.payment",
            ),
        ),
    ]
