# Generated by Django 4.2.7 on 2023-11-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["id"], name="purchase_id_b397cf_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["lesson"], name="purchase_lesson__e5a7b1_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["lecturer"], name="purchase_lecture_9a07fb_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["student", "lesson", "lecturer"],
                name="purchase_student_09a831_idx",
            ),
        ),
    ]
