# Generated by Django 4.2.7 on 2024-10-03 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0002_payment_purchase_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="purchase.payment"
            ),
        ),
    ]
