# Generated by Django 4.2.7 on 2024-10-18 10:02

from django.db import migrations, models
import django.db.models.deletion
import purchase.models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0002_alter_lessonpricehistory_lesson"),
        ("profile", "0004_create_dummy_student"),
        ("purchase", "0003_alter_purchase_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_lesson",
                to="lesson.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_payment",
                to="purchase.payment",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="student",
            field=models.ForeignKey(
                on_delete=models.SET(purchase.models.get_dummy_student_profile),
                related_name="purchase_student",
                to="profile.studentprofile",
            ),
        ),
    ]
