# Generated by Django 4.2.16 on 2025-02-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0004_alter_purchase_lesson_alter_purchase_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[("PLN", "PLN"), ("EUR", "EUR"), ("USD", "USD")],
                default="PLN",
                max_length=3,
            ),
        ),
    ]
