# Generated by Django 4.2.16 on 2025-02-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0005_payment_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("Przelewy24", "Przelewy24"),
                    ("PayPal", "PayPal"),
                    ("Przelew", "Przelew"),
                ],
                default="Przelew",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(null=True),
        ),
    ]
