# Generated by Django 4.2.16 on 2025-02-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0005_payment_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("Przelewy24", "Przelewy24")],
                default="Przelewy24",
                max_length=10,
            ),
        ),
    ]
