# Generated by Django 4.2.16 on 2025-02-13 09:42

from django.db import migrations, models
import django.db.models.deletion
import purchase.models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0006_create_dummy_other"),
        ("service", "0001_initial"),
        ("purchase", "0006_payment_method_payment_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "other",
                    models.ForeignKey(
                        on_delete=models.SET(purchase.models.get_dummy_other_profile),
                        related_name="service_purchase_other",
                        to="profile.otherprofile",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_purchase_payment",
                        to="purchase.payment",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_purchase_service",
                        to="service.service",
                    ),
                ),
            ],
            options={
                "db_table": "service_purchase",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="service_pur_id_8a973f_idx"),
                    models.Index(
                        fields=["service"], name="service_pur_service_b35968_idx"
                    ),
                    models.Index(
                        fields=["other", "service"],
                        name="service_pur_other_i_25ae4a_idx",
                    ),
                ],
            },
        ),
    ]
