# Generated by Django 4.2.16 on 2025-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0007_servicepurchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[("PLN", "Pln"), ("EUR", "Eur"), ("USD", "Usd")],
                default="PLN",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("Przelewy24", "Przelewy24"),
                    ("PayPal", "Paypal"),
                    ("Przelew", "Bank Transfer"),
                ],
                default="Przelew",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Success", "Success"),
                    ("Failure", "Failure"),
                ],
                default="Pending",
            ),
        ),
    ]
