# Generated by Django 4.2.7 on 2024-09-08 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile", "0004_create_dummy_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "type",
                    models.CharField(
                        choices=[("L", "Lekcja"), ("M", "Moduł"), ("K", "Kurs")],
                        default="L",
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                ("title", models.CharField()),
                ("duration", models.PositiveIntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_student",
                        to="profile.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "certificate",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="certificate_id_760fd9_idx"),
                    models.Index(
                        fields=["student"], name="certificate_student_dea57d_idx"
                    ),
                ],
            },
        ),
    ]
