# Generated by Django 4.2.16 on 2025-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="type",
            field=models.CharField(
                choices=[("Lekcja", "Lesson"), ("Moduł", "Module"), ("Kurs", "Course")],
                default="Lekcja",
            ),
        ),
    ]
