apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
spec:
  selector:
    app: pgbouncer
  ports:
    - port: 6432
      targetPort: 6432
