# Generated by Django 4.2.16 on 2024-12-07 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="Tag",
        ),
        migrations.RenameIndex(
            model_name="tag",
            new_name="tags_id_988efd_idx",
            old_name="skill_id_0bf196_idx",
        ),
        migrations.RenameIndex(
            model_name="tag",
            new_name="tags_name_38920e_idx",
            old_name="skill_name_e8acf2_idx",
        ),
        migrations.AlterModelTable(
            name="tag",
            table="tags",
        ),
    ]
