# Generated by Django 4.2.7 on 2023-11-21 20:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("profile", "0002_create_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review", models.TextField(null=True)),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_lecturer",
                        to="profile.profile",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.lesson"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_student",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "review",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="review_id_ea7b6f_idx"),
                    models.Index(fields=["lesson"], name="review_lesson__992cdb_idx"),
                    models.Index(fields=["lecturer"], name="review_lecture_0069cc_idx"),
                    models.Index(fields=["rating"], name="review_rating_d6a32f_idx"),
                    models.Index(
                        fields=["rating", "review"], name="review_rating_04cb9f_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("lesson", "student", "lecturer"),
                name="review_lesson_student_lecturer_unique_together",
            ),
        ),
    ]
