# Generated by Django 4.2.7 on 2024-02-11 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="review_lesson_student_lecturer_unique_together",
        ),
    ]
