# Generated by Django 4.2.7 on 2023-11-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["id"], name="review_id_ea7b6f_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["lesson"], name="review_lesson__992cdb_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["lecturer"], name="review_lecture_0069cc_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="review_rating_d6a32f_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["rating", "review"], name="review_rating_04cb9f_idx"
            ),
        ),
    ]
