apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: loopedupl/backend:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: backend-config
