apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediafiles-pvc
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: mediafiles-pv
