apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediafiles-pv
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
