apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticfiles-pv
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/src/app/backend/static"
