# Generated by Django 4.2.7 on 2024-07-10 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profile.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "join_type",
                    models.CharField(
                        choices=[
                            ("Email", "Email"),
                            ("Google", "Google"),
                            ("Facebook", "Facebook"),
                            ("GitHub", "GitHub"),
                        ],
                        default="Email",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("S", "Student"), ("W", "Wykładowca"), ("A", "Admin")],
                        default="S",
                    ),
                ),
                ("verification_code", models.CharField(max_length=8, null=True)),
                ("verification_code_created_at", models.DateTimeField(null=True)),
                ("phone_number", models.CharField(blank=True, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Mężczyzna"), ("K", "Kobieta"), ("I", "Inne")],
                        default="I",
                    ),
                ),
                ("street_address", models.CharField(blank=True, null=True)),
                ("zip_code", models.CharField(blank=True, null=True)),
                ("city", models.CharField(blank=True, null=True)),
                ("country", models.CharField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=profile.models.user_directory_path,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LecturerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "lecturer_profile",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "admin_profile",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "student_profile",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="student_pro_id_c28073_idx"),
                    models.Index(
                        fields=["profile"], name="student_pro_profile_498b66_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["id"], name="profile_id_bc21b5_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="profile_user_id_2c597b_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user_type"], name="profile_user_ty_cf9e12_idx"),
        ),
        migrations.AddIndex(
            model_name="lecturerprofile",
            index=models.Index(fields=["id"], name="lecturer_pr_id_213b6f_idx"),
        ),
        migrations.AddIndex(
            model_name="lecturerprofile",
            index=models.Index(
                fields=["profile"], name="lecturer_pr_profile_4fed49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminprofile",
            index=models.Index(fields=["id"], name="admin_profi_id_97c42e_idx"),
        ),
        migrations.AddIndex(
            model_name="adminprofile",
            index=models.Index(
                fields=["profile"], name="admin_profi_profile_10a0c7_idx"
            ),
        ),
    ]
