# Generated by Django 4.2.5 on 2023-10-04 07:55

from django.db import migrations
from django.contrib.auth import get_user_model
from django.conf import settings


def generate_superuser(apps, schema_editor):
    email = settings.ADMIN_EMAIL
    password = settings.ADMIN_PASSWORD

    user = get_user_model()

    if not user.objects.filter(email=email).exists():
        admin = user.objects.create_superuser(
            username=email, password=password, email=email
        )
        admin.save()


class Migration(migrations.Migration):
    dependencies = []

    operations = [migrations.RunPython(generate_superuser)]
