# Generated by Django 4.2.7 on 2024-04-21 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profile.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "join_type",
                    models.CharField(
                        choices=[
                            ("Email", "Email"),
                            ("Goggle", "Goggle"),
                            ("Facebook", "Facebook"),
                            ("GitHub", "GitHub"),
                        ],
                        default="Email",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("S", "Student"), ("W", "Wykładowca"), ("A", "Admin")],
                        default="S",
                    ),
                ),
                ("user_title", models.CharField(blank=True, null=True)),
                ("verification_code", models.CharField(max_length=8, null=True)),
                ("verification_code_created_at", models.DateTimeField(null=True)),
                ("phone_number", models.CharField(blank=True, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Mężczyzna"), ("K", "Kobieta"), ("I", "Inne")],
                        default="I",
                    ),
                ),
                ("street_address", models.CharField(blank=True, null=True)),
                ("zip_code", models.CharField(blank=True, null=True)),
                ("city", models.CharField(blank=True, null=True)),
                ("country", models.CharField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=profile.models.user_directory_path,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="profile_id_bc21b5_idx"),
                    models.Index(fields=["user"], name="profile_user_id_2c597b_idx"),
                    models.Index(
                        fields=["user_type"], name="profile_user_ty_cf9e12_idx"
                    ),
                ],
            },
        ),
    ]
