# Generated by Django 4.2.5 on 2023-10-10 08:50

from django.db import migrations
from django.contrib.auth import get_user_model
from django.conf import settings
from profile.models import Profile


def generate_superuser(apps, schema_editor):
    email = settings.ADMIN_EMAIL
    password = settings.ADMIN_PASSWORD

    user = get_user_model()

    if not user.objects.filter(email=email).exists():
        admin = user.objects.create_superuser(
            username=email, password=password, email=email
        )
        admin.save()

        Profile.objects.create(user=admin, user_type="A")


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [migrations.RunPython(generate_superuser)]
