# Generated by Django 4.2.7 on 2024-01-09 11:09

from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0002_create_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Mężczyzna"), ("K", "Kobieta"), ("I", "Inne")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=profile.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="street_address",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_title",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zip_code",
            field=models.CharField(blank=True, null=True),
        ),
    ]
