# Generated by Django 4.2.7 on 2023-11-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0002_create_superuser"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["id"], name="profile_id_bc21b5_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="profile_user_id_2c597b_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user_type"], name="profile_user_ty_cf9e12_idx"),
        ),
    ]
