# Generated by Django 4.2.16 on 2025-02-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0004_create_dummy_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("S", "Student"),
                    ("W", "Wykładowca"),
                    ("A", "Admin"),
                    ("I", "Inny"),
                ],
                default="S",
            ),
        ),
        migrations.CreateModel(
            name="OtherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "other_profile",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="other_profi_id_77b794_idx"),
                    models.Index(
                        fields=["profile"], name="other_profi_profile_2036a3_idx"
                    ),
                ],
            },
        ),
    ]
