# Generated by Django 4.2.16 on 2025-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0006_create_dummy_other"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mężczyzna", "Male"),
                    ("Kobieta", "Female"),
                    ("Inne", "Other"),
                ],
                default="Inne",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="join_type",
            field=models.CharField(
                choices=[
                    ("Email", "Email"),
                    ("Google", "Google"),
                    ("Facebook", "Facebook"),
                    ("GitHub", "Github"),
                ],
                default="Email",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Wykładowca", "Instructor"),
                    ("Admin", "Admin"),
                    ("Inny", "Other"),
                ],
                default="Student",
            ),
        ),
    ]
