name: GithubCI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  lint_backend:
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/backend

    runs-on: ubuntu-latest 

    container: python:3.9-slim

    steps:
      - uses: actions/checkout@v2
      - run: apt-get update
      - run: apt-get -y install libpq-dev gcc
      - run: pip install psycopg2
      - run: pip install --upgrade pip
      - run: pip install -r requirements_lint.txt 
      - run: pip install -r requirements.txt 
      - run: pylint backend --recursive=true --fail-under=10
      - run: black . --check

  test_backend:
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/backend

    runs-on: ubuntu-latest 

    container: python:3.9-slim

    env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: postgres
        DB_PASSWORD: postgres

        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

        EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        
        REDIS_LOCATION: redis://redis:6379/?db=0
        REDIS_PASSWORD:

    services:
      postgres:
        image: postgres:12.5
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - run: apt-get update
      - run: apt-get -y install libpq-dev gcc
      - run: pip install psycopg2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test
       